### ISSUE TITLE
generic type from PERSISTENCE raises ClassCastException

### ISSUE THREAD

**Issue by jonashao** [VictorAlbertos/RxCache#83] opened 2017-02-27 04:31 UTC
I use Retrofit + RxCache + AutoValue + auto-value-gson

```
       GsonConverterFactory converterFactory = GsonConverterFactory.create(
                new GsonBuilder()
                        .registerTypeAdapterFactory(AutoValueGsonFactory.create())
                        .create());

        gankService = new Retrofit.Builder()
                .client(setupOkHttpClient())
                .addConverterFactory(converterFactory)
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .baseUrl(BASE_URL).build().create(GankService.class);

        gankCacheProvider = new RxCache.Builder()
                .persistence(cacheDir, new GsonSpeaker())
                .using(GankCache.class);
```

loading generic type object from MEMORY and CLOUD both works well, but it gets this exception when loading from PERSISTENCE:

java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.junnanhao.gank.data.models.Gank

**Comment by VictorAlbertos** [comment] 2017-03-07 21:34
Duplicate of #73

**Closed as completed by VictorAlbertos** 2017-03-07 21:34 UTC
