### ISSUE TITLE
if the filed of the entity has generic ,like T data,i ,get some err

### ISSUE THREAD

**Issue by DFZYL** [VictorAlbertos/RxCache#74] opened 2016-12-30 01:46 UTC
...com.google.gson.internal.LinkedTreeMap cannot be cast to ...

**Comment by VictorAlbertos** [comment] 2016-12-30 11:21
Duplicate of #73

**Closed as completed by VictorAlbertos** 2016-12-30 11:21 UTC

**Comment by DFZYL** [comment] 2017-01-05 02:25
3ks
