### ISSUE TITLE
about  RxCache  cache  logic

### ISSUE THREAD

**Issue by MathiasLuo** [VictorAlbertos/RxCache#91] opened 2017-06-05 02:52 UTC
There is a problem that bothers me that  I will lost my cache when I get data from internet failed
even if  the original has been cached

**Comment by VictorAlbertos** [comment] 2017-06-06 20:01
Duplicate of #88 

Anyway, you can prevent this just by handling the error in the stream before calling the cache.

**Closed as completed by VictorAlbertos** 2017-06-06 20:01 UTC
